# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_entrega_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entrega_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
