# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190222_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entrega_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
