# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20190226_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='approved_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='author',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumimage',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='albumimage', to='blog.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(upload_to='blog/images/'),
        ),
    ]
