# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190226_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='album',
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Post'),
        ),
    ]
