# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190226_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AlbumImage',
        ),
    ]
