# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190226_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Sube una imagen respecto al tema, luego nuestro personal lo verificara y lo subira'),
        ),
    ]
